### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/Result.cpp#1]
- [x] Consider introducing `result::ok` and `result:err` that would return `OkType` and `ErrType` that can be converted to Result
- [ ] Implement all combinators of [Result](https://doc.rust-lang.org/std/result/enum.Result.html)
- [ ] Would also be nice to make this trivially copyable and trivially destructible if both T and E are
- [ ] Noexcept semantics for all methods
